/* Autogenerated File! Do Not Edit */

type StrNum = string | number;

/* AccessibleBiddingStrategy */
export type AccessibleBiddingStrategyResourceName =
  `customers/${StrNum}/accessibleBiddingStrategies/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} biddingStrategyId
 * @returns `AccessibleBiddingStrategyResourceName`
 * @example const accessibleBiddingStrategy: ResourceNames.AccessibleBiddingStrategyResourceName = ResourceNames.accessibleBiddingStrategy(10987417, 21974834)
 */
export function accessibleBiddingStrategy(
  customerId: string | number,
  biddingStrategyId: string | number
): AccessibleBiddingStrategyResourceName {
  return `customers/${customerId}/accessibleBiddingStrategies/${biddingStrategyId}` as const;
}

/* AccountBudget */
export type AccountBudgetResourceName =
  `customers/${StrNum}/accountBudgets/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} accountBudgetId
 * @returns `AccountBudgetResourceName`
 * @example const accountBudget: ResourceNames.AccountBudgetResourceName = ResourceNames.accountBudget(10987417, 21974834)
 */
export function accountBudget(
  customerId: string | number,
  accountBudgetId: string | number
): AccountBudgetResourceName {
  return `customers/${customerId}/accountBudgets/${accountBudgetId}` as const;
}

/* AccountBudgetProposal */
export type AccountBudgetProposalResourceName =
  `customers/${StrNum}/accountBudgetProposals/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} accountBudgetProposalId
 * @returns `AccountBudgetProposalResourceName`
 * @example const accountBudgetProposal: ResourceNames.AccountBudgetProposalResourceName = ResourceNames.accountBudgetProposal(10987417, 21974834)
 */
export function accountBudgetProposal(
  customerId: string | number,
  accountBudgetProposalId: string | number
): AccountBudgetProposalResourceName {
  return `customers/${customerId}/accountBudgetProposals/${accountBudgetProposalId}` as const;
}

/* AccountLink */
export type AccountLinkResourceName =
  `customers/${StrNum}/accountLinks/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} accountLinkId
 * @returns `AccountLinkResourceName`
 * @example const accountLink: ResourceNames.AccountLinkResourceName = ResourceNames.accountLink(10987417, 21974834)
 */
export function accountLink(
  customerId: string | number,
  accountLinkId: string | number
): AccountLinkResourceName {
  return `customers/${customerId}/accountLinks/${accountLinkId}` as const;
}

/* Ad */
export type AdResourceName = `customers/${StrNum}/ads/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adId
 * @returns `AdResourceName`
 * @example const ad: ResourceNames.AdResourceName = ResourceNames.ad(10987417, 21974834)
 */
export function ad(
  customerId: string | number,
  adId: string | number
): AdResourceName {
  return `customers/${customerId}/ads/${adId}` as const;
}

/* AdGroup */
export type AdGroupResourceName = `customers/${StrNum}/adGroups/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @returns `AdGroupResourceName`
 * @example const adGroup: ResourceNames.AdGroupResourceName = ResourceNames.adGroup(10987417, 21974834)
 */
export function adGroup(
  customerId: string | number,
  adGroupId: string | number
): AdGroupResourceName {
  return `customers/${customerId}/adGroups/${adGroupId}` as const;
}

/* AdGroupAd */
export type AdGroupAdResourceName =
  `customers/${StrNum}/adGroupAds/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} adId
 * @returns `AdGroupAdResourceName`
 * @example const adGroupAd: ResourceNames.AdGroupAdResourceName = ResourceNames.adGroupAd(10987417, 21974834, 43949668)
 */
export function adGroupAd(
  customerId: string | number,
  adGroupId: string | number,
  adId: string | number
): AdGroupAdResourceName {
  return `customers/${customerId}/adGroupAds/${adGroupId}~${adId}` as const;
}

/* AdGroupAdAssetView */
export type AdGroupAdAssetViewResourceName =
  `customers/${StrNum}/adGroupAdAssetViews/${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} adId
 * @param {string | number} assetId
 * @param {string | number} fieldType
 * @returns `AdGroupAdAssetViewResourceName`
 * @example const adGroupAdAssetView: ResourceNames.AdGroupAdAssetViewResourceName = ResourceNames.adGroupAdAssetView(10987417, 21974834, 43949668, 87899336, 175798672)
 */
export function adGroupAdAssetView(
  customerId: string | number,
  adGroupId: string | number,
  adId: string | number,
  assetId: string | number,
  fieldType: string | number
): AdGroupAdAssetViewResourceName {
  return `customers/${customerId}/adGroupAdAssetViews/${adGroupId}~${adId}~${assetId}~${fieldType}` as const;
}

/* AdGroupAdLabel */
export type AdGroupAdLabelResourceName =
  `customers/${StrNum}/adGroupAdLabels/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} adId
 * @param {string | number} labelId
 * @returns `AdGroupAdLabelResourceName`
 * @example const adGroupAdLabel: ResourceNames.AdGroupAdLabelResourceName = ResourceNames.adGroupAdLabel(10987417, 21974834, 43949668, 87899336)
 */
export function adGroupAdLabel(
  customerId: string | number,
  adGroupId: string | number,
  adId: string | number,
  labelId: string | number
): AdGroupAdLabelResourceName {
  return `customers/${customerId}/adGroupAdLabels/${adGroupId}~${adId}~${labelId}` as const;
}

/* AdGroupAsset */
export type AdGroupAssetResourceName =
  `customers/${StrNum}/adGroupAssets/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} assetId
 * @param {string | number} fieldType
 * @returns `AdGroupAssetResourceName`
 * @example const adGroupAsset: ResourceNames.AdGroupAssetResourceName = ResourceNames.adGroupAsset(10987417, 21974834, 43949668, 87899336)
 */
export function adGroupAsset(
  customerId: string | number,
  adGroupId: string | number,
  assetId: string | number,
  fieldType: string | number
): AdGroupAssetResourceName {
  return `customers/${customerId}/adGroupAssets/${adGroupId}~${assetId}~${fieldType}` as const;
}

/* AdGroupAudienceView */
export type AdGroupAudienceViewResourceName =
  `customers/${StrNum}/adGroupAudienceViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `AdGroupAudienceViewResourceName`
 * @example const adGroupAudienceView: ResourceNames.AdGroupAudienceViewResourceName = ResourceNames.adGroupAudienceView(10987417, 21974834, 43949668)
 */
export function adGroupAudienceView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): AdGroupAudienceViewResourceName {
  return `customers/${customerId}/adGroupAudienceViews/${adGroupId}~${criterionId}` as const;
}

/* AdGroupBidModifier */
export type AdGroupBidModifierResourceName =
  `customers/${StrNum}/adGroupBidModifiers/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `AdGroupBidModifierResourceName`
 * @example const adGroupBidModifier: ResourceNames.AdGroupBidModifierResourceName = ResourceNames.adGroupBidModifier(10987417, 21974834, 43949668)
 */
export function adGroupBidModifier(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): AdGroupBidModifierResourceName {
  return `customers/${customerId}/adGroupBidModifiers/${adGroupId}~${criterionId}` as const;
}

/* AdGroupCriterion */
export type AdGroupCriterionResourceName =
  `customers/${StrNum}/adGroupCriteria/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `AdGroupCriterionResourceName`
 * @example const adGroupCriterion: ResourceNames.AdGroupCriterionResourceName = ResourceNames.adGroupCriterion(10987417, 21974834, 43949668)
 */
export function adGroupCriterion(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): AdGroupCriterionResourceName {
  return `customers/${customerId}/adGroupCriteria/${adGroupId}~${criterionId}` as const;
}

/* AdGroupCriterionLabel */
export type AdGroupCriterionLabelResourceName =
  `customers/${StrNum}/adGroupCriterionLabels/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @param {string | number} labelId
 * @returns `AdGroupCriterionLabelResourceName`
 * @example const adGroupCriterionLabel: ResourceNames.AdGroupCriterionLabelResourceName = ResourceNames.adGroupCriterionLabel(10987417, 21974834, 43949668, 87899336)
 */
export function adGroupCriterionLabel(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number,
  labelId: string | number
): AdGroupCriterionLabelResourceName {
  return `customers/${customerId}/adGroupCriterionLabels/${adGroupId}~${criterionId}~${labelId}` as const;
}

/* AdGroupCriterionSimulation */
export type AdGroupCriterionSimulationResourceName =
  `customers/${StrNum}/adGroupCriterionSimulations/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @param {string | number} type
 * @param {string | number} modificationMethod
 * @param {string | number} startDate
 * @param {string | number} endDate
 * @returns `AdGroupCriterionSimulationResourceName`
 * @example const adGroupCriterionSimulation: ResourceNames.AdGroupCriterionSimulationResourceName = ResourceNames.adGroupCriterionSimulation(10987417, 21974834, 43949668, 87899336, 175798672, 351597344, 703194688)
 */
export function adGroupCriterionSimulation(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number,
  type: string | number,
  modificationMethod: string | number,
  startDate: string | number,
  endDate: string | number
): AdGroupCriterionSimulationResourceName {
  return `customers/${customerId}/adGroupCriterionSimulations/${adGroupId}~${criterionId}~${type}~${modificationMethod}~${startDate}~${endDate}` as const;
}

/* AdGroupExtensionSetting */
export type AdGroupExtensionSettingResourceName =
  `customers/${StrNum}/adGroupExtensionSettings/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} extensionType
 * @returns `AdGroupExtensionSettingResourceName`
 * @example const adGroupExtensionSetting: ResourceNames.AdGroupExtensionSettingResourceName = ResourceNames.adGroupExtensionSetting(10987417, 21974834, 43949668)
 */
export function adGroupExtensionSetting(
  customerId: string | number,
  adGroupId: string | number,
  extensionType: string | number
): AdGroupExtensionSettingResourceName {
  return `customers/${customerId}/adGroupExtensionSettings/${adGroupId}~${extensionType}` as const;
}

/* AdGroupFeed */
export type AdGroupFeedResourceName =
  `customers/${StrNum}/adGroupFeeds/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} feedId
 * @returns `AdGroupFeedResourceName`
 * @example const adGroupFeed: ResourceNames.AdGroupFeedResourceName = ResourceNames.adGroupFeed(10987417, 21974834, 43949668)
 */
export function adGroupFeed(
  customerId: string | number,
  adGroupId: string | number,
  feedId: string | number
): AdGroupFeedResourceName {
  return `customers/${customerId}/adGroupFeeds/${adGroupId}~${feedId}` as const;
}

/* AdGroupLabel */
export type AdGroupLabelResourceName =
  `customers/${StrNum}/adGroupLabels/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} labelId
 * @returns `AdGroupLabelResourceName`
 * @example const adGroupLabel: ResourceNames.AdGroupLabelResourceName = ResourceNames.adGroupLabel(10987417, 21974834, 43949668)
 */
export function adGroupLabel(
  customerId: string | number,
  adGroupId: string | number,
  labelId: string | number
): AdGroupLabelResourceName {
  return `customers/${customerId}/adGroupLabels/${adGroupId}~${labelId}` as const;
}

/* AdGroupSimulation */
export type AdGroupSimulationResourceName =
  `customers/${StrNum}/adGroupSimulations/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} type
 * @param {string | number} modificationMethod
 * @param {string | number} startDate
 * @param {string | number} endDate
 * @returns `AdGroupSimulationResourceName`
 * @example const adGroupSimulation: ResourceNames.AdGroupSimulationResourceName = ResourceNames.adGroupSimulation(10987417, 21974834, 43949668, 87899336, 175798672, 351597344)
 */
export function adGroupSimulation(
  customerId: string | number,
  adGroupId: string | number,
  type: string | number,
  modificationMethod: string | number,
  startDate: string | number,
  endDate: string | number
): AdGroupSimulationResourceName {
  return `customers/${customerId}/adGroupSimulations/${adGroupId}~${type}~${modificationMethod}~${startDate}~${endDate}` as const;
}

/* AdParameter */
export type AdParameterResourceName =
  `customers/${StrNum}/adParameters/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @param {string | number} parameterIndex
 * @returns `AdParameterResourceName`
 * @example const adParameter: ResourceNames.AdParameterResourceName = ResourceNames.adParameter(10987417, 21974834, 43949668, 87899336)
 */
export function adParameter(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number,
  parameterIndex: string | number
): AdParameterResourceName {
  return `customers/${customerId}/adParameters/${adGroupId}~${criterionId}~${parameterIndex}` as const;
}

/* AdScheduleView */
export type AdScheduleViewResourceName =
  `customers/${StrNum}/adScheduleViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @returns `AdScheduleViewResourceName`
 * @example const adScheduleView: ResourceNames.AdScheduleViewResourceName = ResourceNames.adScheduleView(10987417, 21974834, 43949668)
 */
export function adScheduleView(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number
): AdScheduleViewResourceName {
  return `customers/${customerId}/adScheduleViews/${campaignId}~${criterionId}` as const;
}

/* AgeRangeView */
export type AgeRangeViewResourceName =
  `customers/${StrNum}/ageRangeViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `AgeRangeViewResourceName`
 * @example const ageRangeView: ResourceNames.AgeRangeViewResourceName = ResourceNames.ageRangeView(10987417, 21974834, 43949668)
 */
export function ageRangeView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): AgeRangeViewResourceName {
  return `customers/${customerId}/ageRangeViews/${adGroupId}~${criterionId}` as const;
}

/* Asset */
export type AssetResourceName = `customers/${StrNum}/assets/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} assetId
 * @returns `AssetResourceName`
 * @example const asset: ResourceNames.AssetResourceName = ResourceNames.asset(10987417, 21974834)
 */
export function asset(
  customerId: string | number,
  assetId: string | number
): AssetResourceName {
  return `customers/${customerId}/assets/${assetId}` as const;
}

/* AssetFieldTypeView */
export type AssetFieldTypeViewResourceName =
  `customers/${StrNum}/assetFieldTypeViews/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} fieldType
 * @returns `AssetFieldTypeViewResourceName`
 * @example const assetFieldTypeView: ResourceNames.AssetFieldTypeViewResourceName = ResourceNames.assetFieldTypeView(10987417, 21974834)
 */
export function assetFieldTypeView(
  customerId: string | number,
  fieldType: string | number
): AssetFieldTypeViewResourceName {
  return `customers/${customerId}/assetFieldTypeViews/${fieldType}` as const;
}

/* BatchJob */
export type BatchJobResourceName = `customers/${StrNum}/batchJobs/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} batchJobId
 * @returns `BatchJobResourceName`
 * @example const batchJob: ResourceNames.BatchJobResourceName = ResourceNames.batchJob(10987417, 21974834)
 */
export function batchJob(
  customerId: string | number,
  batchJobId: string | number
): BatchJobResourceName {
  return `customers/${customerId}/batchJobs/${batchJobId}` as const;
}

/* BiddingDataExclusion */
export type BiddingDataExclusionResourceName =
  `customers/${StrNum}/biddingDataExclusions/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} seasonalityEventId
 * @returns `BiddingDataExclusionResourceName`
 * @example const biddingDataExclusion: ResourceNames.BiddingDataExclusionResourceName = ResourceNames.biddingDataExclusion(10987417, 21974834)
 */
export function biddingDataExclusion(
  customerId: string | number,
  seasonalityEventId: string | number
): BiddingDataExclusionResourceName {
  return `customers/${customerId}/biddingDataExclusions/${seasonalityEventId}` as const;
}

/* BiddingSeasonalityAdjustment */
export type BiddingSeasonalityAdjustmentResourceName =
  `customers/${StrNum}/biddingSeasonalityAdjustments/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} seasonalityEventId
 * @returns `BiddingSeasonalityAdjustmentResourceName`
 * @example const biddingSeasonalityAdjustment: ResourceNames.BiddingSeasonalityAdjustmentResourceName = ResourceNames.biddingSeasonalityAdjustment(10987417, 21974834)
 */
export function biddingSeasonalityAdjustment(
  customerId: string | number,
  seasonalityEventId: string | number
): BiddingSeasonalityAdjustmentResourceName {
  return `customers/${customerId}/biddingSeasonalityAdjustments/${seasonalityEventId}` as const;
}

/* BiddingStrategy */
export type BiddingStrategyResourceName =
  `customers/${StrNum}/biddingStrategies/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} biddingStrategyId
 * @returns `BiddingStrategyResourceName`
 * @example const biddingStrategy: ResourceNames.BiddingStrategyResourceName = ResourceNames.biddingStrategy(10987417, 21974834)
 */
export function biddingStrategy(
  customerId: string | number,
  biddingStrategyId: string | number
): BiddingStrategyResourceName {
  return `customers/${customerId}/biddingStrategies/${biddingStrategyId}` as const;
}

/* BiddingStrategySimulation */
export type BiddingStrategySimulationResourceName =
  `customers/${StrNum}/biddingStrategySimulations/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} biddingStrategyId
 * @param {string | number} type
 * @param {string | number} modificationMethod
 * @param {string | number} startDate
 * @param {string | number} endDate
 * @returns `BiddingStrategySimulationResourceName`
 * @example const biddingStrategySimulation: ResourceNames.BiddingStrategySimulationResourceName = ResourceNames.biddingStrategySimulation(10987417, 21974834, 43949668, 87899336, 175798672, 351597344)
 */
export function biddingStrategySimulation(
  customerId: string | number,
  biddingStrategyId: string | number,
  type: string | number,
  modificationMethod: string | number,
  startDate: string | number,
  endDate: string | number
): BiddingStrategySimulationResourceName {
  return `customers/${customerId}/biddingStrategySimulations/${biddingStrategyId}~${type}~${modificationMethod}~${startDate}~${endDate}` as const;
}

/* BillingSetup */
export type BillingSetupResourceName =
  `customers/${StrNum}/billingSetups/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} billingSetupId
 * @returns `BillingSetupResourceName`
 * @example const billingSetup: ResourceNames.BillingSetupResourceName = ResourceNames.billingSetup(10987417, 21974834)
 */
export function billingSetup(
  customerId: string | number,
  billingSetupId: string | number
): BillingSetupResourceName {
  return `customers/${customerId}/billingSetups/${billingSetupId}` as const;
}

/* CallView */
export type CallViewResourceName = `customers/${StrNum}/callViews/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} callDetailId
 * @returns `CallViewResourceName`
 * @example const callView: ResourceNames.CallViewResourceName = ResourceNames.callView(10987417, 21974834)
 */
export function callView(
  customerId: string | number,
  callDetailId: string | number
): CallViewResourceName {
  return `customers/${customerId}/callViews/${callDetailId}` as const;
}

/* Campaign */
export type CampaignResourceName = `customers/${StrNum}/campaigns/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @returns `CampaignResourceName`
 * @example const campaign: ResourceNames.CampaignResourceName = ResourceNames.campaign(10987417, 21974834)
 */
export function campaign(
  customerId: string | number,
  campaignId: string | number
): CampaignResourceName {
  return `customers/${customerId}/campaigns/${campaignId}` as const;
}

/* CampaignAsset */
export type CampaignAssetResourceName =
  `customers/${StrNum}/campaignAssets/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} assetId
 * @param {string | number} fieldType
 * @returns `CampaignAssetResourceName`
 * @example const campaignAsset: ResourceNames.CampaignAssetResourceName = ResourceNames.campaignAsset(10987417, 21974834, 43949668, 87899336)
 */
export function campaignAsset(
  customerId: string | number,
  campaignId: string | number,
  assetId: string | number,
  fieldType: string | number
): CampaignAssetResourceName {
  return `customers/${customerId}/campaignAssets/${campaignId}~${assetId}~${fieldType}` as const;
}

/* CampaignAudienceView */
export type CampaignAudienceViewResourceName =
  `customers/${StrNum}/campaignAudienceViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @returns `CampaignAudienceViewResourceName`
 * @example const campaignAudienceView: ResourceNames.CampaignAudienceViewResourceName = ResourceNames.campaignAudienceView(10987417, 21974834, 43949668)
 */
export function campaignAudienceView(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number
): CampaignAudienceViewResourceName {
  return `customers/${customerId}/campaignAudienceViews/${campaignId}~${criterionId}` as const;
}

/* CampaignBidModifier */
export type CampaignBidModifierResourceName =
  `customers/${StrNum}/campaignBidModifiers/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @returns `CampaignBidModifierResourceName`
 * @example const campaignBidModifier: ResourceNames.CampaignBidModifierResourceName = ResourceNames.campaignBidModifier(10987417, 21974834, 43949668)
 */
export function campaignBidModifier(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number
): CampaignBidModifierResourceName {
  return `customers/${customerId}/campaignBidModifiers/${campaignId}~${criterionId}` as const;
}

/* CampaignBudget */
export type CampaignBudgetResourceName =
  `customers/${StrNum}/campaignBudgets/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignBudgetId
 * @returns `CampaignBudgetResourceName`
 * @example const campaignBudget: ResourceNames.CampaignBudgetResourceName = ResourceNames.campaignBudget(10987417, 21974834)
 */
export function campaignBudget(
  customerId: string | number,
  campaignBudgetId: string | number
): CampaignBudgetResourceName {
  return `customers/${customerId}/campaignBudgets/${campaignBudgetId}` as const;
}

/* CampaignCriterion */
export type CampaignCriterionResourceName =
  `customers/${StrNum}/campaignCriteria/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @returns `CampaignCriterionResourceName`
 * @example const campaignCriterion: ResourceNames.CampaignCriterionResourceName = ResourceNames.campaignCriterion(10987417, 21974834, 43949668)
 */
export function campaignCriterion(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number
): CampaignCriterionResourceName {
  return `customers/${customerId}/campaignCriteria/${campaignId}~${criterionId}` as const;
}

/* CampaignCriterionSimulation */
export type CampaignCriterionSimulationResourceName =
  `customers/${StrNum}/campaignCriterionSimulations/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @param {string | number} type
 * @param {string | number} modificationMethod
 * @param {string | number} startDate
 * @param {string | number} endDate
 * @returns `CampaignCriterionSimulationResourceName`
 * @example const campaignCriterionSimulation: ResourceNames.CampaignCriterionSimulationResourceName = ResourceNames.campaignCriterionSimulation(10987417, 21974834, 43949668, 87899336, 175798672, 351597344, 703194688)
 */
export function campaignCriterionSimulation(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number,
  type: string | number,
  modificationMethod: string | number,
  startDate: string | number,
  endDate: string | number
): CampaignCriterionSimulationResourceName {
  return `customers/${customerId}/campaignCriterionSimulations/${campaignId}~${criterionId}~${type}~${modificationMethod}~${startDate}~${endDate}` as const;
}

/* CampaignDraft */
export type CampaignDraftResourceName =
  `customers/${StrNum}/campaignDrafts/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} baseCampaignId
 * @param {string | number} draftId
 * @returns `CampaignDraftResourceName`
 * @example const campaignDraft: ResourceNames.CampaignDraftResourceName = ResourceNames.campaignDraft(10987417, 21974834, 43949668)
 */
export function campaignDraft(
  customerId: string | number,
  baseCampaignId: string | number,
  draftId: string | number
): CampaignDraftResourceName {
  return `customers/${customerId}/campaignDrafts/${baseCampaignId}~${draftId}` as const;
}

/* CampaignExperiment */
export type CampaignExperimentResourceName =
  `customers/${StrNum}/campaignExperiments/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignExperimentId
 * @returns `CampaignExperimentResourceName`
 * @example const campaignExperiment: ResourceNames.CampaignExperimentResourceName = ResourceNames.campaignExperiment(10987417, 21974834)
 */
export function campaignExperiment(
  customerId: string | number,
  campaignExperimentId: string | number
): CampaignExperimentResourceName {
  return `customers/${customerId}/campaignExperiments/${campaignExperimentId}` as const;
}

/* CampaignExtensionSetting */
export type CampaignExtensionSettingResourceName =
  `customers/${StrNum}/campaignExtensionSettings/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} extensionType
 * @returns `CampaignExtensionSettingResourceName`
 * @example const campaignExtensionSetting: ResourceNames.CampaignExtensionSettingResourceName = ResourceNames.campaignExtensionSetting(10987417, 21974834, 43949668)
 */
export function campaignExtensionSetting(
  customerId: string | number,
  campaignId: string | number,
  extensionType: string | number
): CampaignExtensionSettingResourceName {
  return `customers/${customerId}/campaignExtensionSettings/${campaignId}~${extensionType}` as const;
}

/* CampaignFeed */
export type CampaignFeedResourceName =
  `customers/${StrNum}/campaignFeeds/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} feedId
 * @returns `CampaignFeedResourceName`
 * @example const campaignFeed: ResourceNames.CampaignFeedResourceName = ResourceNames.campaignFeed(10987417, 21974834, 43949668)
 */
export function campaignFeed(
  customerId: string | number,
  campaignId: string | number,
  feedId: string | number
): CampaignFeedResourceName {
  return `customers/${customerId}/campaignFeeds/${campaignId}~${feedId}` as const;
}

/* CampaignLabel */
export type CampaignLabelResourceName =
  `customers/${StrNum}/campaignLabels/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} labelId
 * @returns `CampaignLabelResourceName`
 * @example const campaignLabel: ResourceNames.CampaignLabelResourceName = ResourceNames.campaignLabel(10987417, 21974834, 43949668)
 */
export function campaignLabel(
  customerId: string | number,
  campaignId: string | number,
  labelId: string | number
): CampaignLabelResourceName {
  return `customers/${customerId}/campaignLabels/${campaignId}~${labelId}` as const;
}

/* CampaignSharedSet */
export type CampaignSharedSetResourceName =
  `customers/${StrNum}/campaignSharedSets/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} sharedSetId
 * @returns `CampaignSharedSetResourceName`
 * @example const campaignSharedSet: ResourceNames.CampaignSharedSetResourceName = ResourceNames.campaignSharedSet(10987417, 21974834, 43949668)
 */
export function campaignSharedSet(
  customerId: string | number,
  campaignId: string | number,
  sharedSetId: string | number
): CampaignSharedSetResourceName {
  return `customers/${customerId}/campaignSharedSets/${campaignId}~${sharedSetId}` as const;
}

/* CampaignSimulation */
export type CampaignSimulationResourceName =
  `customers/${StrNum}/campaignSimulations/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} type
 * @param {string | number} modificationMethod
 * @param {string | number} startDate
 * @param {string | number} endDate
 * @returns `CampaignSimulationResourceName`
 * @example const campaignSimulation: ResourceNames.CampaignSimulationResourceName = ResourceNames.campaignSimulation(10987417, 21974834, 43949668, 87899336, 175798672, 351597344)
 */
export function campaignSimulation(
  customerId: string | number,
  campaignId: string | number,
  type: string | number,
  modificationMethod: string | number,
  startDate: string | number,
  endDate: string | number
): CampaignSimulationResourceName {
  return `customers/${customerId}/campaignSimulations/${campaignId}~${type}~${modificationMethod}~${startDate}~${endDate}` as const;
}

/* CarrierConstant */
export type CarrierConstantResourceName = `carrierConstants/${StrNum}`;
/**
 * @param {string | number} criterionId
 * @returns `CarrierConstantResourceName`
 * @example const carrierConstant: ResourceNames.CarrierConstantResourceName = ResourceNames.carrierConstant(10987417)
 */
export function carrierConstant(
  criterionId: string | number
): CarrierConstantResourceName {
  return `carrierConstants/${criterionId}` as const;
}

/* ChangeEvent */
export type ChangeEventResourceName =
  `customers/${StrNum}/changeEvents/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} timestampMicros
 * @param {string | number} commandIndex
 * @param {string | number} mutateIndex
 * @returns `ChangeEventResourceName`
 * @example const changeEvent: ResourceNames.ChangeEventResourceName = ResourceNames.changeEvent(10987417, 21974834, 43949668, 87899336)
 */
export function changeEvent(
  customerId: string | number,
  timestampMicros: string | number,
  commandIndex: string | number,
  mutateIndex: string | number
): ChangeEventResourceName {
  return `customers/${customerId}/changeEvents/${timestampMicros}~${commandIndex}~${mutateIndex}` as const;
}

/* ChangeStatus */
export type ChangeStatusResourceName =
  `customers/${StrNum}/changeStatus/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} changeStatusId
 * @returns `ChangeStatusResourceName`
 * @example const changeStatus: ResourceNames.ChangeStatusResourceName = ResourceNames.changeStatus(10987417, 21974834)
 */
export function changeStatus(
  customerId: string | number,
  changeStatusId: string | number
): ChangeStatusResourceName {
  return `customers/${customerId}/changeStatus/${changeStatusId}` as const;
}

/* ClickView */
export type ClickViewResourceName =
  `customers/${StrNum}/clickViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} date
 * @param {string | number} gclid
 * @returns `ClickViewResourceName`
 * @example const clickView: ResourceNames.ClickViewResourceName = ResourceNames.clickView(10987417, 21974834, 43949668)
 */
export function clickView(
  customerId: string | number,
  date: string | number,
  gclid: string | number
): ClickViewResourceName {
  return `customers/${customerId}/clickViews/${date}~${gclid}` as const;
}

/* CombinedAudience */
export type CombinedAudienceResourceName =
  `customers/${StrNum}/combinedAudiences/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} combinedAudienceId
 * @returns `CombinedAudienceResourceName`
 * @example const combinedAudience: ResourceNames.CombinedAudienceResourceName = ResourceNames.combinedAudience(10987417, 21974834)
 */
export function combinedAudience(
  customerId: string | number,
  combinedAudienceId: string | number
): CombinedAudienceResourceName {
  return `customers/${customerId}/combinedAudiences/${combinedAudienceId}` as const;
}

/* ConversionAction */
export type ConversionActionResourceName =
  `customers/${StrNum}/conversionActions/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} conversionActionId
 * @returns `ConversionActionResourceName`
 * @example const conversionAction: ResourceNames.ConversionActionResourceName = ResourceNames.conversionAction(10987417, 21974834)
 */
export function conversionAction(
  customerId: string | number,
  conversionActionId: string | number
): ConversionActionResourceName {
  return `customers/${customerId}/conversionActions/${conversionActionId}` as const;
}

/* ConversionCustomVariable */
export type ConversionCustomVariableResourceName =
  `customers/${StrNum}/conversionCustomVariables/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} conversionCustomVariableId
 * @returns `ConversionCustomVariableResourceName`
 * @example const conversionCustomVariable: ResourceNames.ConversionCustomVariableResourceName = ResourceNames.conversionCustomVariable(10987417, 21974834)
 */
export function conversionCustomVariable(
  customerId: string | number,
  conversionCustomVariableId: string | number
): ConversionCustomVariableResourceName {
  return `customers/${customerId}/conversionCustomVariables/${conversionCustomVariableId}` as const;
}

/* ConversionValueRule */
export type ConversionValueRuleResourceName =
  `customers/${StrNum}/conversionValueRules/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} conversionValueRuleId
 * @returns `ConversionValueRuleResourceName`
 * @example const conversionValueRule: ResourceNames.ConversionValueRuleResourceName = ResourceNames.conversionValueRule(10987417, 21974834)
 */
export function conversionValueRule(
  customerId: string | number,
  conversionValueRuleId: string | number
): ConversionValueRuleResourceName {
  return `customers/${customerId}/conversionValueRules/${conversionValueRuleId}` as const;
}

/* ConversionValueRuleSet */
export type ConversionValueRuleSetResourceName =
  `customers/${StrNum}/conversionValueRuleSets/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} conversionValueRuleSetId
 * @returns `ConversionValueRuleSetResourceName`
 * @example const conversionValueRuleSet: ResourceNames.ConversionValueRuleSetResourceName = ResourceNames.conversionValueRuleSet(10987417, 21974834)
 */
export function conversionValueRuleSet(
  customerId: string | number,
  conversionValueRuleSetId: string | number
): ConversionValueRuleSetResourceName {
  return `customers/${customerId}/conversionValueRuleSets/${conversionValueRuleSetId}` as const;
}

/* CurrencyConstant */
export type CurrencyConstantResourceName = `currencyConstants/${StrNum}`;
/**
 * @param {string | number} code
 * @returns `CurrencyConstantResourceName`
 * @example const currencyConstant: ResourceNames.CurrencyConstantResourceName = ResourceNames.currencyConstant(10987417)
 */
export function currencyConstant(
  code: string | number
): CurrencyConstantResourceName {
  return `currencyConstants/${code}` as const;
}

/* CustomAudience */
export type CustomAudienceResourceName =
  `customers/${StrNum}/customAudiences/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} customAudienceId
 * @returns `CustomAudienceResourceName`
 * @example const customAudience: ResourceNames.CustomAudienceResourceName = ResourceNames.customAudience(10987417, 21974834)
 */
export function customAudience(
  customerId: string | number,
  customAudienceId: string | number
): CustomAudienceResourceName {
  return `customers/${customerId}/customAudiences/${customAudienceId}` as const;
}

/* CustomInterest */
export type CustomInterestResourceName =
  `customers/${StrNum}/customInterests/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} customInterestId
 * @returns `CustomInterestResourceName`
 * @example const customInterest: ResourceNames.CustomInterestResourceName = ResourceNames.customInterest(10987417, 21974834)
 */
export function customInterest(
  customerId: string | number,
  customInterestId: string | number
): CustomInterestResourceName {
  return `customers/${customerId}/customInterests/${customInterestId}` as const;
}

/* Customer */
export type CustomerResourceName = `customers/${StrNum}`;
/**
 * @param {string | number} customerId
 * @returns `CustomerResourceName`
 * @example const customer: ResourceNames.CustomerResourceName = ResourceNames.customer(10987417)
 */
export function customer(customerId: string | number): CustomerResourceName {
  return `customers/${customerId}` as const;
}

/* CustomerAsset */
export type CustomerAssetResourceName =
  `customers/${StrNum}/customerAssets/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} assetId
 * @param {string | number} fieldType
 * @returns `CustomerAssetResourceName`
 * @example const customerAsset: ResourceNames.CustomerAssetResourceName = ResourceNames.customerAsset(10987417, 21974834, 43949668)
 */
export function customerAsset(
  customerId: string | number,
  assetId: string | number,
  fieldType: string | number
): CustomerAssetResourceName {
  return `customers/${customerId}/customerAssets/${assetId}~${fieldType}` as const;
}

/* CustomerClient */
export type CustomerClientResourceName =
  `customers/${StrNum}/customerClients/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} clientCustomerId
 * @returns `CustomerClientResourceName`
 * @example const customerClient: ResourceNames.CustomerClientResourceName = ResourceNames.customerClient(10987417, 21974834)
 */
export function customerClient(
  customerId: string | number,
  clientCustomerId: string | number
): CustomerClientResourceName {
  return `customers/${customerId}/customerClients/${clientCustomerId}` as const;
}

/* CustomerClientLink */
export type CustomerClientLinkResourceName =
  `customers/${StrNum}/customerClientLinks/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} clientCustomerId
 * @param {string | number} managerLinkId
 * @returns `CustomerClientLinkResourceName`
 * @example const customerClientLink: ResourceNames.CustomerClientLinkResourceName = ResourceNames.customerClientLink(10987417, 21974834, 43949668)
 */
export function customerClientLink(
  customerId: string | number,
  clientCustomerId: string | number,
  managerLinkId: string | number
): CustomerClientLinkResourceName {
  return `customers/${customerId}/customerClientLinks/${clientCustomerId}~${managerLinkId}` as const;
}

/* CustomerExtensionSetting */
export type CustomerExtensionSettingResourceName =
  `customers/${StrNum}/customerExtensionSettings/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} extensionType
 * @returns `CustomerExtensionSettingResourceName`
 * @example const customerExtensionSetting: ResourceNames.CustomerExtensionSettingResourceName = ResourceNames.customerExtensionSetting(10987417, 21974834)
 */
export function customerExtensionSetting(
  customerId: string | number,
  extensionType: string | number
): CustomerExtensionSettingResourceName {
  return `customers/${customerId}/customerExtensionSettings/${extensionType}` as const;
}

/* CustomerFeed */
export type CustomerFeedResourceName =
  `customers/${StrNum}/customerFeeds/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @returns `CustomerFeedResourceName`
 * @example const customerFeed: ResourceNames.CustomerFeedResourceName = ResourceNames.customerFeed(10987417, 21974834)
 */
export function customerFeed(
  customerId: string | number,
  feedId: string | number
): CustomerFeedResourceName {
  return `customers/${customerId}/customerFeeds/${feedId}` as const;
}

/* CustomerLabel */
export type CustomerLabelResourceName =
  `customers/${StrNum}/customerLabels/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} labelId
 * @returns `CustomerLabelResourceName`
 * @example const customerLabel: ResourceNames.CustomerLabelResourceName = ResourceNames.customerLabel(10987417, 21974834)
 */
export function customerLabel(
  customerId: string | number,
  labelId: string | number
): CustomerLabelResourceName {
  return `customers/${customerId}/customerLabels/${labelId}` as const;
}

/* CustomerManagerLink */
export type CustomerManagerLinkResourceName =
  `customers/${StrNum}/customerManagerLinks/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} managerCustomerId
 * @param {string | number} managerLinkId
 * @returns `CustomerManagerLinkResourceName`
 * @example const customerManagerLink: ResourceNames.CustomerManagerLinkResourceName = ResourceNames.customerManagerLink(10987417, 21974834, 43949668)
 */
export function customerManagerLink(
  customerId: string | number,
  managerCustomerId: string | number,
  managerLinkId: string | number
): CustomerManagerLinkResourceName {
  return `customers/${customerId}/customerManagerLinks/${managerCustomerId}~${managerLinkId}` as const;
}

/* CustomerNegativeCriterion */
export type CustomerNegativeCriterionResourceName =
  `customers/${StrNum}/customerNegativeCriteria/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} criterionId
 * @returns `CustomerNegativeCriterionResourceName`
 * @example const customerNegativeCriterion: ResourceNames.CustomerNegativeCriterionResourceName = ResourceNames.customerNegativeCriterion(10987417, 21974834)
 */
export function customerNegativeCriterion(
  customerId: string | number,
  criterionId: string | number
): CustomerNegativeCriterionResourceName {
  return `customers/${customerId}/customerNegativeCriteria/${criterionId}` as const;
}

/* CustomerUserAccess */
export type CustomerUserAccessResourceName =
  `customers/${StrNum}/customerUserAccesses/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} userId
 * @returns `CustomerUserAccessResourceName`
 * @example const customerUserAccess: ResourceNames.CustomerUserAccessResourceName = ResourceNames.customerUserAccess(10987417, 21974834)
 */
export function customerUserAccess(
  customerId: string | number,
  userId: string | number
): CustomerUserAccessResourceName {
  return `customers/${customerId}/customerUserAccesses/${userId}` as const;
}

/* CustomerUserAccessInvitation */
export type CustomerUserAccessInvitationResourceName =
  `customers/${StrNum}/customerUserAccessInvitations/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} invitationId
 * @returns `CustomerUserAccessInvitationResourceName`
 * @example const customerUserAccessInvitation: ResourceNames.CustomerUserAccessInvitationResourceName = ResourceNames.customerUserAccessInvitation(10987417, 21974834)
 */
export function customerUserAccessInvitation(
  customerId: string | number,
  invitationId: string | number
): CustomerUserAccessInvitationResourceName {
  return `customers/${customerId}/customerUserAccessInvitations/${invitationId}` as const;
}

/* DetailPlacementView */
export type DetailPlacementViewResourceName =
  `customers/${StrNum}/detailPlacementViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} base64Placement
 * @returns `DetailPlacementViewResourceName`
 * @example const detailPlacementView: ResourceNames.DetailPlacementViewResourceName = ResourceNames.detailPlacementView(10987417, 21974834, 43949668)
 */
export function detailPlacementView(
  customerId: string | number,
  adGroupId: string | number,
  base64Placement: string | number
): DetailPlacementViewResourceName {
  return `customers/${customerId}/detailPlacementViews/${adGroupId}~${base64Placement}` as const;
}

/* DetailedDemographic */
export type DetailedDemographicResourceName =
  `customers/${StrNum}/detailedDemographics/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} detailedDemographicId
 * @returns `DetailedDemographicResourceName`
 * @example const detailedDemographic: ResourceNames.DetailedDemographicResourceName = ResourceNames.detailedDemographic(10987417, 21974834)
 */
export function detailedDemographic(
  customerId: string | number,
  detailedDemographicId: string | number
): DetailedDemographicResourceName {
  return `customers/${customerId}/detailedDemographics/${detailedDemographicId}` as const;
}

/* DisplayKeywordView */
export type DisplayKeywordViewResourceName =
  `customers/${StrNum}/displayKeywordViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `DisplayKeywordViewResourceName`
 * @example const displayKeywordView: ResourceNames.DisplayKeywordViewResourceName = ResourceNames.displayKeywordView(10987417, 21974834, 43949668)
 */
export function displayKeywordView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): DisplayKeywordViewResourceName {
  return `customers/${customerId}/displayKeywordViews/${adGroupId}~${criterionId}` as const;
}

/* DistanceView */
export type DistanceViewResourceName =
  `customers/${StrNum}/distanceViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} placeholderChainId
 * @param {string | number} distanceBucket
 * @returns `DistanceViewResourceName`
 * @example const distanceView: ResourceNames.DistanceViewResourceName = ResourceNames.distanceView(10987417, 21974834, 43949668)
 */
export function distanceView(
  customerId: string | number,
  placeholderChainId: string | number,
  distanceBucket: string | number
): DistanceViewResourceName {
  return `customers/${customerId}/distanceViews/${placeholderChainId}~${distanceBucket}` as const;
}

/* DomainCategory */
export type DomainCategoryResourceName =
  `customers/${StrNum}/domainCategories/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} base64Category
 * @param {string | number} languageCode
 * @returns `DomainCategoryResourceName`
 * @example const domainCategory: ResourceNames.DomainCategoryResourceName = ResourceNames.domainCategory(10987417, 21974834, 43949668, 87899336)
 */
export function domainCategory(
  customerId: string | number,
  campaignId: string | number,
  base64Category: string | number,
  languageCode: string | number
): DomainCategoryResourceName {
  return `customers/${customerId}/domainCategories/${campaignId}~${base64Category}~${languageCode}` as const;
}

/* DynamicSearchAdsSearchTermView */
export type DynamicSearchAdsSearchTermViewResourceName =
  `customers/${StrNum}/dynamicSearchAdsSearchTermViews/${StrNum}~${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} searchTermFingerprint
 * @param {string | number} headlineFingerprint
 * @param {string | number} landingPageFingerprint
 * @param {string | number} pageUrlFingerprint
 * @returns `DynamicSearchAdsSearchTermViewResourceName`
 * @example const dynamicSearchAdsSearchTermView: ResourceNames.DynamicSearchAdsSearchTermViewResourceName = ResourceNames.dynamicSearchAdsSearchTermView(10987417, 21974834, 43949668, 87899336, 175798672, 351597344)
 */
export function dynamicSearchAdsSearchTermView(
  customerId: string | number,
  adGroupId: string | number,
  searchTermFingerprint: string | number,
  headlineFingerprint: string | number,
  landingPageFingerprint: string | number,
  pageUrlFingerprint: string | number
): DynamicSearchAdsSearchTermViewResourceName {
  return `customers/${customerId}/dynamicSearchAdsSearchTermViews/${adGroupId}~${searchTermFingerprint}~${headlineFingerprint}~${landingPageFingerprint}~${pageUrlFingerprint}` as const;
}

/* ExpandedLandingPageView */
export type ExpandedLandingPageViewResourceName =
  `customers/${StrNum}/expandedLandingPageViews/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} expandedFinalUrlFingerprint
 * @returns `ExpandedLandingPageViewResourceName`
 * @example const expandedLandingPageView: ResourceNames.ExpandedLandingPageViewResourceName = ResourceNames.expandedLandingPageView(10987417, 21974834)
 */
export function expandedLandingPageView(
  customerId: string | number,
  expandedFinalUrlFingerprint: string | number
): ExpandedLandingPageViewResourceName {
  return `customers/${customerId}/expandedLandingPageViews/${expandedFinalUrlFingerprint}` as const;
}

/* ExtensionFeedItem */
export type ExtensionFeedItemResourceName =
  `customers/${StrNum}/extensionFeedItems/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedItemId
 * @returns `ExtensionFeedItemResourceName`
 * @example const extensionFeedItem: ResourceNames.ExtensionFeedItemResourceName = ResourceNames.extensionFeedItem(10987417, 21974834)
 */
export function extensionFeedItem(
  customerId: string | number,
  feedItemId: string | number
): ExtensionFeedItemResourceName {
  return `customers/${customerId}/extensionFeedItems/${feedItemId}` as const;
}

/* Feed */
export type FeedResourceName = `customers/${StrNum}/feeds/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @returns `FeedResourceName`
 * @example const feed: ResourceNames.FeedResourceName = ResourceNames.feed(10987417, 21974834)
 */
export function feed(
  customerId: string | number,
  feedId: string | number
): FeedResourceName {
  return `customers/${customerId}/feeds/${feedId}` as const;
}

/* FeedItem */
export type FeedItemResourceName =
  `customers/${StrNum}/feedItems/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @param {string | number} feedItemId
 * @returns `FeedItemResourceName`
 * @example const feedItem: ResourceNames.FeedItemResourceName = ResourceNames.feedItem(10987417, 21974834, 43949668)
 */
export function feedItem(
  customerId: string | number,
  feedId: string | number,
  feedItemId: string | number
): FeedItemResourceName {
  return `customers/${customerId}/feedItems/${feedId}~${feedItemId}` as const;
}

/* FeedItemSet */
export type FeedItemSetResourceName =
  `customers/${StrNum}/feedItemSets/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @param {string | number} feedItemSetId
 * @returns `FeedItemSetResourceName`
 * @example const feedItemSet: ResourceNames.FeedItemSetResourceName = ResourceNames.feedItemSet(10987417, 21974834, 43949668)
 */
export function feedItemSet(
  customerId: string | number,
  feedId: string | number,
  feedItemSetId: string | number
): FeedItemSetResourceName {
  return `customers/${customerId}/feedItemSets/${feedId}~${feedItemSetId}` as const;
}

/* FeedItemSetLink */
export type FeedItemSetLinkResourceName =
  `customers/${StrNum}/feedItemSetLinks/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @param {string | number} feedItemSetId
 * @param {string | number} feedItemId
 * @returns `FeedItemSetLinkResourceName`
 * @example const feedItemSetLink: ResourceNames.FeedItemSetLinkResourceName = ResourceNames.feedItemSetLink(10987417, 21974834, 43949668, 87899336)
 */
export function feedItemSetLink(
  customerId: string | number,
  feedId: string | number,
  feedItemSetId: string | number,
  feedItemId: string | number
): FeedItemSetLinkResourceName {
  return `customers/${customerId}/feedItemSetLinks/${feedId}~${feedItemSetId}~${feedItemId}` as const;
}

/* FeedItemTarget */
export type FeedItemTargetResourceName =
  `customers/${StrNum}/feedItemTargets/${StrNum}~${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @param {string | number} feedItemId
 * @param {string | number} feedItemTargetType
 * @param {string | number} feedItemTargetId
 * @returns `FeedItemTargetResourceName`
 * @example const feedItemTarget: ResourceNames.FeedItemTargetResourceName = ResourceNames.feedItemTarget(10987417, 21974834, 43949668, 87899336, 175798672)
 */
export function feedItemTarget(
  customerId: string | number,
  feedId: string | number,
  feedItemId: string | number,
  feedItemTargetType: string | number,
  feedItemTargetId: string | number
): FeedItemTargetResourceName {
  return `customers/${customerId}/feedItemTargets/${feedId}~${feedItemId}~${feedItemTargetType}~${feedItemTargetId}` as const;
}

/* FeedMapping */
export type FeedMappingResourceName =
  `customers/${StrNum}/feedMappings/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} feedId
 * @param {string | number} feedMappingId
 * @returns `FeedMappingResourceName`
 * @example const feedMapping: ResourceNames.FeedMappingResourceName = ResourceNames.feedMapping(10987417, 21974834, 43949668)
 */
export function feedMapping(
  customerId: string | number,
  feedId: string | number,
  feedMappingId: string | number
): FeedMappingResourceName {
  return `customers/${customerId}/feedMappings/${feedId}~${feedMappingId}` as const;
}

/* FeedPlaceholderView */
export type FeedPlaceholderViewResourceName =
  `customers/${StrNum}/feedPlaceholderViews/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} placeholderType
 * @returns `FeedPlaceholderViewResourceName`
 * @example const feedPlaceholderView: ResourceNames.FeedPlaceholderViewResourceName = ResourceNames.feedPlaceholderView(10987417, 21974834)
 */
export function feedPlaceholderView(
  customerId: string | number,
  placeholderType: string | number
): FeedPlaceholderViewResourceName {
  return `customers/${customerId}/feedPlaceholderViews/${placeholderType}` as const;
}

/* GenderView */
export type GenderViewResourceName =
  `customers/${StrNum}/genderViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `GenderViewResourceName`
 * @example const genderView: ResourceNames.GenderViewResourceName = ResourceNames.genderView(10987417, 21974834, 43949668)
 */
export function genderView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): GenderViewResourceName {
  return `customers/${customerId}/genderViews/${adGroupId}~${criterionId}` as const;
}

/* GeoTargetConstant */
export type GeoTargetConstantResourceName = `geoTargetConstants/${StrNum}`;
/**
 * @param {string | number} criterionId
 * @returns `GeoTargetConstantResourceName`
 * @example const geoTargetConstant: ResourceNames.GeoTargetConstantResourceName = ResourceNames.geoTargetConstant(10987417)
 */
export function geoTargetConstant(
  criterionId: string | number
): GeoTargetConstantResourceName {
  return `geoTargetConstants/${criterionId}` as const;
}

/* GeographicView */
export type GeographicViewResourceName =
  `customers/${StrNum}/geographicViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} countryCriterionId
 * @param {string | number} locationType
 * @returns `GeographicViewResourceName`
 * @example const geographicView: ResourceNames.GeographicViewResourceName = ResourceNames.geographicView(10987417, 21974834, 43949668)
 */
export function geographicView(
  customerId: string | number,
  countryCriterionId: string | number,
  locationType: string | number
): GeographicViewResourceName {
  return `customers/${customerId}/geographicViews/${countryCriterionId}~${locationType}` as const;
}

/* GoogleAdsField */
export type GoogleAdsFieldResourceName = `googleAdsFields/${StrNum}`;
/**
 * @param {string | number} googleAdsField
 * @returns `GoogleAdsFieldResourceName`
 * @example const googleAdsField: ResourceNames.GoogleAdsFieldResourceName = ResourceNames.googleAdsField(10987417)
 */
export function googleAdsField(
  googleAdsField: string | number
): GoogleAdsFieldResourceName {
  return `googleAdsFields/${googleAdsField}` as const;
}

/* GroupPlacementView */
export type GroupPlacementViewResourceName =
  `customers/${StrNum}/groupPlacementViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} base64Placement
 * @returns `GroupPlacementViewResourceName`
 * @example const groupPlacementView: ResourceNames.GroupPlacementViewResourceName = ResourceNames.groupPlacementView(10987417, 21974834, 43949668)
 */
export function groupPlacementView(
  customerId: string | number,
  adGroupId: string | number,
  base64Placement: string | number
): GroupPlacementViewResourceName {
  return `customers/${customerId}/groupPlacementViews/${adGroupId}~${base64Placement}` as const;
}

/* HotelGroupView */
export type HotelGroupViewResourceName =
  `customers/${StrNum}/hotelGroupViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `HotelGroupViewResourceName`
 * @example const hotelGroupView: ResourceNames.HotelGroupViewResourceName = ResourceNames.hotelGroupView(10987417, 21974834, 43949668)
 */
export function hotelGroupView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): HotelGroupViewResourceName {
  return `customers/${customerId}/hotelGroupViews/${adGroupId}~${criterionId}` as const;
}

/* HotelPerformanceView */
export type HotelPerformanceViewResourceName =
  `customers/${StrNum}/hotelPerformanceView`;
/**
 * @param {string | number} customerId
 * @returns `HotelPerformanceViewResourceName`
 * @example const hotelPerformanceView: ResourceNames.HotelPerformanceViewResourceName = ResourceNames.hotelPerformanceView(10987417)
 */
export function hotelPerformanceView(
  customerId: string | number
): HotelPerformanceViewResourceName {
  return `customers/${customerId}/hotelPerformanceView` as const;
}

/* IncomeRangeView */
export type IncomeRangeViewResourceName =
  `customers/${StrNum}/incomeRangeViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `IncomeRangeViewResourceName`
 * @example const incomeRangeView: ResourceNames.IncomeRangeViewResourceName = ResourceNames.incomeRangeView(10987417, 21974834, 43949668)
 */
export function incomeRangeView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): IncomeRangeViewResourceName {
  return `customers/${customerId}/incomeRangeViews/${adGroupId}~${criterionId}` as const;
}

/* Invoice */
export type InvoiceResourceName = `customers/${StrNum}/invoices/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} invoiceId
 * @returns `InvoiceResourceName`
 * @example const invoice: ResourceNames.InvoiceResourceName = ResourceNames.invoice(10987417, 21974834)
 */
export function invoice(
  customerId: string | number,
  invoiceId: string | number
): InvoiceResourceName {
  return `customers/${customerId}/invoices/${invoiceId}` as const;
}

/* KeywordPlan */
export type KeywordPlanResourceName =
  `customers/${StrNum}/keywordPlans/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} keywordPlanId
 * @returns `KeywordPlanResourceName`
 * @example const keywordPlan: ResourceNames.KeywordPlanResourceName = ResourceNames.keywordPlan(10987417, 21974834)
 */
export function keywordPlan(
  customerId: string | number,
  keywordPlanId: string | number
): KeywordPlanResourceName {
  return `customers/${customerId}/keywordPlans/${keywordPlanId}` as const;
}

/* KeywordPlanAdGroup */
export type KeywordPlanAdGroupResourceName =
  `customers/${StrNum}/keywordPlanAdGroups/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} keywordPlanAdGroupId
 * @returns `KeywordPlanAdGroupResourceName`
 * @example const keywordPlanAdGroup: ResourceNames.KeywordPlanAdGroupResourceName = ResourceNames.keywordPlanAdGroup(10987417, 21974834)
 */
export function keywordPlanAdGroup(
  customerId: string | number,
  keywordPlanAdGroupId: string | number
): KeywordPlanAdGroupResourceName {
  return `customers/${customerId}/keywordPlanAdGroups/${keywordPlanAdGroupId}` as const;
}

/* KeywordPlanAdGroupKeyword */
export type KeywordPlanAdGroupKeywordResourceName =
  `customers/${StrNum}/keywordPlanAdGroupKeywords/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} keywordPlanAdGroupKeywordId
 * @returns `KeywordPlanAdGroupKeywordResourceName`
 * @example const keywordPlanAdGroupKeyword: ResourceNames.KeywordPlanAdGroupKeywordResourceName = ResourceNames.keywordPlanAdGroupKeyword(10987417, 21974834)
 */
export function keywordPlanAdGroupKeyword(
  customerId: string | number,
  keywordPlanAdGroupKeywordId: string | number
): KeywordPlanAdGroupKeywordResourceName {
  return `customers/${customerId}/keywordPlanAdGroupKeywords/${keywordPlanAdGroupKeywordId}` as const;
}

/* KeywordPlanCampaign */
export type KeywordPlanCampaignResourceName =
  `customers/${StrNum}/keywordPlanCampaigns/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} keywordPlanCampaignId
 * @returns `KeywordPlanCampaignResourceName`
 * @example const keywordPlanCampaign: ResourceNames.KeywordPlanCampaignResourceName = ResourceNames.keywordPlanCampaign(10987417, 21974834)
 */
export function keywordPlanCampaign(
  customerId: string | number,
  keywordPlanCampaignId: string | number
): KeywordPlanCampaignResourceName {
  return `customers/${customerId}/keywordPlanCampaigns/${keywordPlanCampaignId}` as const;
}

/* KeywordPlanCampaignKeyword */
export type KeywordPlanCampaignKeywordResourceName =
  `customers/${StrNum}/keywordPlanCampaignKeywords/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} keywordPlanCampaignKeywordId
 * @returns `KeywordPlanCampaignKeywordResourceName`
 * @example const keywordPlanCampaignKeyword: ResourceNames.KeywordPlanCampaignKeywordResourceName = ResourceNames.keywordPlanCampaignKeyword(10987417, 21974834)
 */
export function keywordPlanCampaignKeyword(
  customerId: string | number,
  keywordPlanCampaignKeywordId: string | number
): KeywordPlanCampaignKeywordResourceName {
  return `customers/${customerId}/keywordPlanCampaignKeywords/${keywordPlanCampaignKeywordId}` as const;
}

/* KeywordThemeConstant */
export type KeywordThemeConstantResourceName =
  `keywordThemeConstants/${StrNum}~${StrNum}`;
/**
 * @param {string | number} expressCategoryId
 * @param {string | number} expressSubCategoryId
 * @returns `KeywordThemeConstantResourceName`
 * @example const keywordThemeConstant: ResourceNames.KeywordThemeConstantResourceName = ResourceNames.keywordThemeConstant(10987417, 21974834)
 */
export function keywordThemeConstant(
  expressCategoryId: string | number,
  expressSubCategoryId: string | number
): KeywordThemeConstantResourceName {
  return `keywordThemeConstants/${expressCategoryId}~${expressSubCategoryId}` as const;
}

/* KeywordView */
export type KeywordViewResourceName =
  `customers/${StrNum}/keywordViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `KeywordViewResourceName`
 * @example const keywordView: ResourceNames.KeywordViewResourceName = ResourceNames.keywordView(10987417, 21974834, 43949668)
 */
export function keywordView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): KeywordViewResourceName {
  return `customers/${customerId}/keywordViews/${adGroupId}~${criterionId}` as const;
}

/* Label */
export type LabelResourceName = `customers/${StrNum}/labels/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} labelId
 * @returns `LabelResourceName`
 * @example const label: ResourceNames.LabelResourceName = ResourceNames.label(10987417, 21974834)
 */
export function label(
  customerId: string | number,
  labelId: string | number
): LabelResourceName {
  return `customers/${customerId}/labels/${labelId}` as const;
}

/* LandingPageView */
export type LandingPageViewResourceName =
  `customers/${StrNum}/landingPageViews/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} unexpandedFinalUrlFingerprint
 * @returns `LandingPageViewResourceName`
 * @example const landingPageView: ResourceNames.LandingPageViewResourceName = ResourceNames.landingPageView(10987417, 21974834)
 */
export function landingPageView(
  customerId: string | number,
  unexpandedFinalUrlFingerprint: string | number
): LandingPageViewResourceName {
  return `customers/${customerId}/landingPageViews/${unexpandedFinalUrlFingerprint}` as const;
}

/* LanguageConstant */
export type LanguageConstantResourceName = `languageConstants/${StrNum}`;
/**
 * @param {string | number} criterionId
 * @returns `LanguageConstantResourceName`
 * @example const languageConstant: ResourceNames.LanguageConstantResourceName = ResourceNames.languageConstant(10987417)
 */
export function languageConstant(
  criterionId: string | number
): LanguageConstantResourceName {
  return `languageConstants/${criterionId}` as const;
}

/* LifeEvent */
export type LifeEventResourceName = `customers/${StrNum}/lifeEvents/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} lifeEventId
 * @returns `LifeEventResourceName`
 * @example const lifeEvent: ResourceNames.LifeEventResourceName = ResourceNames.lifeEvent(10987417, 21974834)
 */
export function lifeEvent(
  customerId: string | number,
  lifeEventId: string | number
): LifeEventResourceName {
  return `customers/${customerId}/lifeEvents/${lifeEventId}` as const;
}

/* LocationView */
export type LocationViewResourceName =
  `customers/${StrNum}/locationViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} criterionId
 * @returns `LocationViewResourceName`
 * @example const locationView: ResourceNames.LocationViewResourceName = ResourceNames.locationView(10987417, 21974834, 43949668)
 */
export function locationView(
  customerId: string | number,
  campaignId: string | number,
  criterionId: string | number
): LocationViewResourceName {
  return `customers/${customerId}/locationViews/${campaignId}~${criterionId}` as const;
}

/* ManagedPlacementView */
export type ManagedPlacementViewResourceName =
  `customers/${StrNum}/managedPlacementViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `ManagedPlacementViewResourceName`
 * @example const managedPlacementView: ResourceNames.ManagedPlacementViewResourceName = ResourceNames.managedPlacementView(10987417, 21974834, 43949668)
 */
export function managedPlacementView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): ManagedPlacementViewResourceName {
  return `customers/${customerId}/managedPlacementViews/${adGroupId}~${criterionId}` as const;
}

/* MediaFile */
export type MediaFileResourceName = `customers/${StrNum}/mediaFiles/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} mediaFileId
 * @returns `MediaFileResourceName`
 * @example const mediaFile: ResourceNames.MediaFileResourceName = ResourceNames.mediaFile(10987417, 21974834)
 */
export function mediaFile(
  customerId: string | number,
  mediaFileId: string | number
): MediaFileResourceName {
  return `customers/${customerId}/mediaFiles/${mediaFileId}` as const;
}

/* MerchantCenterLink */
export type MerchantCenterLinkResourceName =
  `customers/${StrNum}/merchantCenterLinks/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} merchantCenterId
 * @returns `MerchantCenterLinkResourceName`
 * @example const merchantCenterLink: ResourceNames.MerchantCenterLinkResourceName = ResourceNames.merchantCenterLink(10987417, 21974834)
 */
export function merchantCenterLink(
  customerId: string | number,
  merchantCenterId: string | number
): MerchantCenterLinkResourceName {
  return `customers/${customerId}/merchantCenterLinks/${merchantCenterId}` as const;
}

/* MobileAppCategoryConstant */
export type MobileAppCategoryConstantResourceName =
  `mobileAppCategoryConstants/${StrNum}`;
/**
 * @param {string | number} mobileAppCategoryId
 * @returns `MobileAppCategoryConstantResourceName`
 * @example const mobileAppCategoryConstant: ResourceNames.MobileAppCategoryConstantResourceName = ResourceNames.mobileAppCategoryConstant(10987417)
 */
export function mobileAppCategoryConstant(
  mobileAppCategoryId: string | number
): MobileAppCategoryConstantResourceName {
  return `mobileAppCategoryConstants/${mobileAppCategoryId}` as const;
}

/* MobileDeviceConstant */
export type MobileDeviceConstantResourceName =
  `mobileDeviceConstants/${StrNum}`;
/**
 * @param {string | number} criterionId
 * @returns `MobileDeviceConstantResourceName`
 * @example const mobileDeviceConstant: ResourceNames.MobileDeviceConstantResourceName = ResourceNames.mobileDeviceConstant(10987417)
 */
export function mobileDeviceConstant(
  criterionId: string | number
): MobileDeviceConstantResourceName {
  return `mobileDeviceConstants/${criterionId}` as const;
}

/* OfflineUserDataJob */
export type OfflineUserDataJobResourceName =
  `customers/${StrNum}/offlineUserDataJobs/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} offlineUserDataUpdateId
 * @returns `OfflineUserDataJobResourceName`
 * @example const offlineUserDataJob: ResourceNames.OfflineUserDataJobResourceName = ResourceNames.offlineUserDataJob(10987417, 21974834)
 */
export function offlineUserDataJob(
  customerId: string | number,
  offlineUserDataUpdateId: string | number
): OfflineUserDataJobResourceName {
  return `customers/${customerId}/offlineUserDataJobs/${offlineUserDataUpdateId}` as const;
}

/* OperatingSystemVersionConstant */
export type OperatingSystemVersionConstantResourceName =
  `operatingSystemVersionConstants/${StrNum}`;
/**
 * @param {string | number} criterionId
 * @returns `OperatingSystemVersionConstantResourceName`
 * @example const operatingSystemVersionConstant: ResourceNames.OperatingSystemVersionConstantResourceName = ResourceNames.operatingSystemVersionConstant(10987417)
 */
export function operatingSystemVersionConstant(
  criterionId: string | number
): OperatingSystemVersionConstantResourceName {
  return `operatingSystemVersionConstants/${criterionId}` as const;
}

/* PaidOrganicSearchTermView */
export type PaidOrganicSearchTermViewResourceName =
  `customers/${StrNum}/paidOrganicSearchTermViews/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} adGroupId
 * @param {string | number} base64SearchTerm
 * @returns `PaidOrganicSearchTermViewResourceName`
 * @example const paidOrganicSearchTermView: ResourceNames.PaidOrganicSearchTermViewResourceName = ResourceNames.paidOrganicSearchTermView(10987417, 21974834, 43949668, 87899336)
 */
export function paidOrganicSearchTermView(
  customerId: string | number,
  campaignId: string | number,
  adGroupId: string | number,
  base64SearchTerm: string | number
): PaidOrganicSearchTermViewResourceName {
  return `customers/${customerId}/paidOrganicSearchTermViews/${campaignId}~${adGroupId}~${base64SearchTerm}` as const;
}

/* ParentalStatusView */
export type ParentalStatusViewResourceName =
  `customers/${StrNum}/parentalStatusViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `ParentalStatusViewResourceName`
 * @example const parentalStatusView: ResourceNames.ParentalStatusViewResourceName = ResourceNames.parentalStatusView(10987417, 21974834, 43949668)
 */
export function parentalStatusView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): ParentalStatusViewResourceName {
  return `customers/${customerId}/parentalStatusViews/${adGroupId}~${criterionId}` as const;
}

/* PaymentsAccount */
export type PaymentsAccountResourceName =
  `customers/${StrNum}/paymentsAccounts/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} paymentsAccountId
 * @returns `PaymentsAccountResourceName`
 * @example const paymentsAccount: ResourceNames.PaymentsAccountResourceName = ResourceNames.paymentsAccount(10987417, 21974834)
 */
export function paymentsAccount(
  customerId: string | number,
  paymentsAccountId: string | number
): PaymentsAccountResourceName {
  return `customers/${customerId}/paymentsAccounts/${paymentsAccountId}` as const;
}

/* ProductBiddingCategoryConstant */
export type ProductBiddingCategoryConstantResourceName =
  `productBiddingCategoryConstants/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} countryCode
 * @param {string | number} level
 * @param {string | number} id
 * @returns `ProductBiddingCategoryConstantResourceName`
 * @example const productBiddingCategoryConstant: ResourceNames.ProductBiddingCategoryConstantResourceName = ResourceNames.productBiddingCategoryConstant(10987417, 21974834, 43949668)
 */
export function productBiddingCategoryConstant(
  countryCode: string | number,
  level: string | number,
  id: string | number
): ProductBiddingCategoryConstantResourceName {
  return `productBiddingCategoryConstants/${countryCode}~${level}~${id}` as const;
}

/* ProductGroupView */
export type ProductGroupViewResourceName =
  `customers/${StrNum}/productGroupViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adgroupId
 * @param {string | number} criterionId
 * @returns `ProductGroupViewResourceName`
 * @example const productGroupView: ResourceNames.ProductGroupViewResourceName = ResourceNames.productGroupView(10987417, 21974834, 43949668)
 */
export function productGroupView(
  customerId: string | number,
  adgroupId: string | number,
  criterionId: string | number
): ProductGroupViewResourceName {
  return `customers/${customerId}/productGroupViews/${adgroupId}~${criterionId}` as const;
}

/* Recommendation */
export type RecommendationResourceName =
  `customers/${StrNum}/recommendations/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} recommendationId
 * @returns `RecommendationResourceName`
 * @example const recommendation: ResourceNames.RecommendationResourceName = ResourceNames.recommendation(10987417, 21974834)
 */
export function recommendation(
  customerId: string | number,
  recommendationId: string | number
): RecommendationResourceName {
  return `customers/${customerId}/recommendations/${recommendationId}` as const;
}

/* RemarketingAction */
export type RemarketingActionResourceName =
  `customers/${StrNum}/remarketingActions/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} remarketingActionId
 * @returns `RemarketingActionResourceName`
 * @example const remarketingAction: ResourceNames.RemarketingActionResourceName = ResourceNames.remarketingAction(10987417, 21974834)
 */
export function remarketingAction(
  customerId: string | number,
  remarketingActionId: string | number
): RemarketingActionResourceName {
  return `customers/${customerId}/remarketingActions/${remarketingActionId}` as const;
}

/* SearchTermView */
export type SearchTermViewResourceName =
  `customers/${StrNum}/searchTermViews/${StrNum}~${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} adGroupId
 * @param {string | number} query
 * @returns `SearchTermViewResourceName`
 * @example const searchTermView: ResourceNames.SearchTermViewResourceName = ResourceNames.searchTermView(10987417, 21974834, 43949668, 87899336)
 */
export function searchTermView(
  customerId: string | number,
  campaignId: string | number,
  adGroupId: string | number,
  query: string | number
): SearchTermViewResourceName {
  return `customers/${customerId}/searchTermViews/${campaignId}~${adGroupId}~${query}` as const;
}

/* SharedCriterion */
export type SharedCriterionResourceName =
  `customers/${StrNum}/sharedCriteria/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} sharedSetId
 * @param {string | number} criterionId
 * @returns `SharedCriterionResourceName`
 * @example const sharedCriterion: ResourceNames.SharedCriterionResourceName = ResourceNames.sharedCriterion(10987417, 21974834, 43949668)
 */
export function sharedCriterion(
  customerId: string | number,
  sharedSetId: string | number,
  criterionId: string | number
): SharedCriterionResourceName {
  return `customers/${customerId}/sharedCriteria/${sharedSetId}~${criterionId}` as const;
}

/* SharedSet */
export type SharedSetResourceName = `customers/${StrNum}/sharedSets/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} sharedSetId
 * @returns `SharedSetResourceName`
 * @example const sharedSet: ResourceNames.SharedSetResourceName = ResourceNames.sharedSet(10987417, 21974834)
 */
export function sharedSet(
  customerId: string | number,
  sharedSetId: string | number
): SharedSetResourceName {
  return `customers/${customerId}/sharedSets/${sharedSetId}` as const;
}

/* ShoppingPerformanceView */
export type ShoppingPerformanceViewResourceName =
  `customers/${StrNum}/shoppingPerformanceView`;
/**
 * @param {string | number} customerId
 * @returns `ShoppingPerformanceViewResourceName`
 * @example const shoppingPerformanceView: ResourceNames.ShoppingPerformanceViewResourceName = ResourceNames.shoppingPerformanceView(10987417)
 */
export function shoppingPerformanceView(
  customerId: string | number
): ShoppingPerformanceViewResourceName {
  return `customers/${customerId}/shoppingPerformanceView` as const;
}

/* SmartCampaignSearchTermView */
export type SmartCampaignSearchTermViewResourceName =
  `customers/${StrNum}/smartCampaignSearchTermViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @param {string | number} query
 * @returns `SmartCampaignSearchTermViewResourceName`
 * @example const smartCampaignSearchTermView: ResourceNames.SmartCampaignSearchTermViewResourceName = ResourceNames.smartCampaignSearchTermView(10987417, 21974834, 43949668)
 */
export function smartCampaignSearchTermView(
  customerId: string | number,
  campaignId: string | number,
  query: string | number
): SmartCampaignSearchTermViewResourceName {
  return `customers/${customerId}/smartCampaignSearchTermViews/${campaignId}~${query}` as const;
}

/* SmartCampaignSetting */
export type SmartCampaignSettingResourceName =
  `customers/${StrNum}/smartCampaignSettings/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} campaignId
 * @returns `SmartCampaignSettingResourceName`
 * @example const smartCampaignSetting: ResourceNames.SmartCampaignSettingResourceName = ResourceNames.smartCampaignSetting(10987417, 21974834)
 */
export function smartCampaignSetting(
  customerId: string | number,
  campaignId: string | number
): SmartCampaignSettingResourceName {
  return `customers/${customerId}/smartCampaignSettings/${campaignId}` as const;
}

/* ThirdPartyAppAnalyticsLink */
export type ThirdPartyAppAnalyticsLinkResourceName =
  `customers/${StrNum}/thirdPartyAppAnalyticsLinks/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} customerLinkId
 * @returns `ThirdPartyAppAnalyticsLinkResourceName`
 * @example const thirdPartyAppAnalyticsLink: ResourceNames.ThirdPartyAppAnalyticsLinkResourceName = ResourceNames.thirdPartyAppAnalyticsLink(10987417, 21974834)
 */
export function thirdPartyAppAnalyticsLink(
  customerId: string | number,
  customerLinkId: string | number
): ThirdPartyAppAnalyticsLinkResourceName {
  return `customers/${customerId}/thirdPartyAppAnalyticsLinks/${customerLinkId}` as const;
}

/* TopicConstant */
export type TopicConstantResourceName = `topicConstants/${StrNum}`;
/**
 * @param {string | number} topicId
 * @returns `TopicConstantResourceName`
 * @example const topicConstant: ResourceNames.TopicConstantResourceName = ResourceNames.topicConstant(10987417)
 */
export function topicConstant(
  topicId: string | number
): TopicConstantResourceName {
  return `topicConstants/${topicId}` as const;
}

/* TopicView */
export type TopicViewResourceName =
  `customers/${StrNum}/topicViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `TopicViewResourceName`
 * @example const topicView: ResourceNames.TopicViewResourceName = ResourceNames.topicView(10987417, 21974834, 43949668)
 */
export function topicView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): TopicViewResourceName {
  return `customers/${customerId}/topicViews/${adGroupId}~${criterionId}` as const;
}

/* UserInterest */
export type UserInterestResourceName =
  `customers/${StrNum}/userInterests/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} userInterestId
 * @returns `UserInterestResourceName`
 * @example const userInterest: ResourceNames.UserInterestResourceName = ResourceNames.userInterest(10987417, 21974834)
 */
export function userInterest(
  customerId: string | number,
  userInterestId: string | number
): UserInterestResourceName {
  return `customers/${customerId}/userInterests/${userInterestId}` as const;
}

/* UserList */
export type UserListResourceName = `customers/${StrNum}/userLists/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} userListId
 * @returns `UserListResourceName`
 * @example const userList: ResourceNames.UserListResourceName = ResourceNames.userList(10987417, 21974834)
 */
export function userList(
  customerId: string | number,
  userListId: string | number
): UserListResourceName {
  return `customers/${customerId}/userLists/${userListId}` as const;
}

/* UserLocationView */
export type UserLocationViewResourceName =
  `customers/${StrNum}/userLocationViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} countryCriterionId
 * @param {string | number} isTargetingLocation
 * @returns `UserLocationViewResourceName`
 * @example const userLocationView: ResourceNames.UserLocationViewResourceName = ResourceNames.userLocationView(10987417, 21974834, 43949668)
 */
export function userLocationView(
  customerId: string | number,
  countryCriterionId: string | number,
  isTargetingLocation: string | number
): UserLocationViewResourceName {
  return `customers/${customerId}/userLocationViews/${countryCriterionId}~${isTargetingLocation}` as const;
}

/* Video */
export type VideoResourceName = `customers/${StrNum}/videos/${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} videoId
 * @returns `VideoResourceName`
 * @example const video: ResourceNames.VideoResourceName = ResourceNames.video(10987417, 21974834)
 */
export function video(
  customerId: string | number,
  videoId: string | number
): VideoResourceName {
  return `customers/${customerId}/videos/${videoId}` as const;
}

/* WebpageView */
export type WebpageViewResourceName =
  `customers/${StrNum}/webpageViews/${StrNum}~${StrNum}`;
/**
 * @param {string | number} customerId
 * @param {string | number} adGroupId
 * @param {string | number} criterionId
 * @returns `WebpageViewResourceName`
 * @example const webpageView: ResourceNames.WebpageViewResourceName = ResourceNames.webpageView(10987417, 21974834, 43949668)
 */
export function webpageView(
  customerId: string | number,
  adGroupId: string | number,
  criterionId: string | number
): WebpageViewResourceName {
  return `customers/${customerId}/webpageViews/${adGroupId}~${criterionId}` as const;
}
